### ISSUE TITLE
Incorrect values being reported for Zen+ Picasso processor

### ISSUE THREAD

**Issue by bimmerdriver** [irusanov/ZenTimings#11]
I'm using ZenTimings 1.2.1 to look at timings for a Ryzen 5 3400G using Gigabyte B450 Aorus M motherboard. ZT is reporting wildly fluctuating FCLK (~1500 to 9000) and it's reporting VSOC, which should be Vcore. Let me know if you need more information, such a debug log.

**Comment by irusanov** [comment]
I have a 3000G and can test it. Newest I have is a 370X board, though.
SVI lanes are probably switched on Picasso, compared to Raven Ridge.
The other issue you have is that the FCLK has s dynamic frequency depending on the load, but I don't know why it reports so high upper limit. I can switch to the other value, which will report the FCLK set value, instead of the dynamic one.
Already did for Renoir, because people were complaining about the variable FCLK.

**Comment by bimmerdriver** [comment]
FCLK is all over the place. At times goes well over 10000.

[Debug_Report_26821083.3408484.txt](https://github.com/irusanov/ZenTimings/files/5751681/Debug_Report_26821083.3408484.txt)

**Comment by irusanov** [comment]
To me it seems a different table version. Would you run a debug with the latest build?
[ZenTimings_v1.2.2.119_debug.zip](https://github.com/irusanov/ZenTimings/files/5752079/ZenTimings_v1.2.2.119_debug.zip)

**Comment by bimmerdriver** [comment]
Here you go. FCLK still jumping around and VSOC is displaying Vcore.

[Debug_Report_26821250.4046665.txt](https://github.com/irusanov/ZenTimings/files/5752138/Debug_Report_26821250.4046665.txt)

**Comment by irusanov** [comment]
Yes, there's no change in the way it reads them, but the newest build includes table version in the debug log.
Thanks, will get back to you when I have a test build.

**Comment by irusanov** [comment]
Your table version is the same as mine, but you have way older SMU version. VSOC looks on on mine, but I guess will need adjustment on your older SMU version bios. Could you check if HWinfo reads SoC Voltage (SVI2 TFN) correctly?

**Comment by bimmerdriver** [comment]
VSOC reported by ZenTimings is CPU Core Voltage (SV12 TFN) reported by HWiNFO v641-4335.

I'm running the most recent available BIOS.

**Comment by irusanov** [comment]
Thanks.
Your bios has SMU version 30.75.00, while mine is running 37.48.00.
Apparently SVI2 addresses changed somewhere between those 2 versions, but without the changelog and documentation I can't know when. In your version the addresses are switched (or from another point of view, they are switched on mine).
HWinfo knows about it, it seems. I can make a fix, but it won't be perfect and will potentially lead to more inconsistency if someone has a bios with different SMU version than these two.

I get why The Stilt abandoned his project long time ago, it's impossible to keep up with all the changes.

**Comment by irusanov** [comment]
Can you, please, check what's the SMU version HWInfo reports?
I have a feeling you might have 4.30.xx.xx version instead.

![image](https://user-images.githubusercontent.com/7671877/103320165-0c9cdf80-4a3d-11eb-9eee-ec741f678a17.png)

**Comment by bimmerdriver** [comment]
Here is the line from HWiNFO: SMU Firmware Revision: 4.30.75.0

Is this out of date? If so, should I open a ticket with Gigabyte and ask if there will be an update?

Thank you for your support.

**Comment by irusanov** [comment]
Ok, as suspected. It's recent enough, I think.
Maybe they are using different firmware, because mine is labeled as Athlon and yours is Ryzen.
Perhaps something to do with the integrated Vega GPU, although both are detected as Picasso.
Might depend on the vendor as well, don't really know.

Thanks for the reports, you helped a ton!

There's a high chance this build works fine now.
[ZenTimings_v1.2.2.120.zip](https://github.com/irusanov/ZenTimings/files/5753824/ZenTimings_v1.2.2.120.zip)

**Comment by bimmerdriver** [comment]
Thank you very much for the fix.

FCLK is stable now. On my system, MCLK, FCLK and UCLK are the same, 1600.

Also, VSOC is stable now at 1.1V, which is the same as HWiNFO. FYI, HWiNFO has two values, a stable value that it reports as SoC Voltave (SV12 TFN), the same as ZenTimings is reporting, as well as a dynamic value that it reports as CPU VCORE SOC.

If you ever need anyone with a 3400G to test, don't hesitate to let me know.

**Comment by irusanov** [comment]
This specific case should be fixed in v1.2.2, although there might be more cases which are not covered.
