### ISSUE TITLE
Missing parameters after BIOS update

### ISSUE THREAD

**Issue by Berlinchild89** [irusanov/ZenTimings#17]
Hi,
first of all thanks for this tool.
So since updating my Asrock B450 Gaming ITX to Agesa 1.2.0.0 there are some parameters missing (they are also missing in Ryzen Master).

When I start Zen timings I get this error: 
Failed to read AMD ACPI. Some parameters will be empty.

I´ve attached a screenshot
![ZenTimings_Screenshot](https://user-images.githubusercontent.com/81927700/113518875-496efa00-9589-11eb-85d8-23daab22a8bc.png)

I´ve also attached a debug report
[Debug_Report_26959375,1301694.txt](https://github.com/irusanov/ZenTimings/files/6255188/Debug_Report_26959375.1301694.txt)

Hope you can help and stay safe

**Comment by irusanov** [comment]
The error usually occurs when bios doesn't expose the AMD_ACPI class in WMI.
However, the debug report shows it's available, but for some reason the response contains just 0 (zeroes).

It's probably bios fault and Asrock messed something up. I have a B350 K4 flashed to B450 and will test it in the weekend.

**Comment by Berlinchild89** [comment]
So any news on this?
Maybe if you have some more infos why it shows zeroes I could forward it over JZ to Asrock?

**Comment by irusanov** [comment]
Unfortunately cross-flashing B350 board with a B450 bios seems to be blocked now, my Asrock B350 K4 board doesn't POST with newest B450 bioses from equivalent boards. They are basically the same board, but the newer AGESA probably detects B350 chipset and artificially halts the initialization.

**Comment by irusanov** [comment]
As for the missing parameters, what probably happens is that the "Get APCB Config" WMI command returns an empty table.
If you open your debug file and then scroll down to the "BIOS: Memory Controller Config" section, you can see the table is empty and the only non-zero values are on index 5 and 19.

WMI seems to be ok, but that command is probably broken or there's an additional parameter which needs to be supplied when executing.

WMI: AMD_ACPI says "OK", the instance name is also correct - "ACPI\PNP0C14\AOD_0"
The ID of the function is reported as Get APCB Config: 00010001

Since it's not working in Ryzen Master (AOD is the old name of the tool and they are still using it internally), the there's nothing I can do. Unfortunately, I can't even confirm it on my old B350 board.

**Comment by Berlinchild89** [comment]
They fixed this with Bios 4.50
