### ISSUE TITLE
Can't compile the new commit

### ISSUE THREAD

**Issue by rmattuschka** [irusanov/ZenTimings#9]
Link to missing "ZenStates.Core.dll" file

**Comment by irusanov** [comment]
Yes, I should have committed to a different branch and not master, since it is still work in progress.
The goal is to move all common functionality to a shared DLL, that will be used in all other apps I have.
Made the DLL source repo public, but keep in mind it is work in progress.

This repo is required to compile the DLL:
https://github.com/irusanov/ZenStates-Core

**Comment by irusanov** [comment]
I have force-pushed the master branch back to 1.2.1 tag and moved the changes to a new branch common-dll, which needs the new repo. Sorry for the inconvenience.

https://github.com/irusanov/ZenTimings/tree/common-dll

**Comment by irusanov** [comment]
New v1.2.2 includes the precompiled dll now, but the source code of the DLL is also available here: https://github.com/irusanov/ZenStates-Core
